### ISSUE TITLE
Docker failing to find executable files within blobtoolkit:latest

### ISSUE THREAD

**Issue by BirdmanRidesAgain** [blobtoolkit/blobtoolkit-docker#7]
Hi,

I'm trying to run blobtoolkit from the docker file, and I'm running into some issues while following the README to get the package up and running.

I ran the pull command (docker pull genomehubs/blobtoolkit) from your docker repository (https://hub.docker.com/r/genomehubs/blobtoolkit), and it seemed to install alright.

The first thing I did was attempt to use the interactive viewer (code below). After specifying the platform (amd64 vs. my default arm64), that had the desired behavior - a container named btk is created and the viewer loads at 'http://localhost:8080/view/all'.

`
docker run -d --rm --name btk
--platform linux/amd64 \
-v /Users/keilercollier/Documents/tools/blobtoolkit/datasets \
-v /Users/keilercollier/Documents/tools/blobtoolkit/output \
-p 8000:8000 -p 8080:8080 \
-e VIEWER=true \
genomehubs/blobtoolkit:latest
`

<br><br>

I then attempted to run the provided code to create a minimal dataset from a local assembly. (A giant clam, in this case.)

`
docker run -it --rm --name btk -u 1000 \
--platform linux/amd64 \
-v /Users/keilercollier/Documents/tools/blobtoolkit/datasets \
-v /Users/keilercollier/Documents/tools/blobtoolkit/databases \
-v /Users/keilercollier/Documents/tools/blobtoolkit/data \
-v /Users/keilercollier/Documents/tools/blobtoolkit/output \
genomehubs/blobtoolkit:latest \
./blobtools2/blobtools create \
--fasta data/Tridacna_squamosina_flye_racon.fasta \
--taxid 484284 \
--taxdump taxdump \
datasets/giant_clam
`

This is the output:
`
docker: Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "./blobtools2/blobtools": stat ./blobtools2/blobtools: no such file or directory: unknown.
`

It doesn't seem to be able to find the directories and I'm not sure how to fix that. Running it without the -u argument (or with my local/root user ID) produces the same output, as does running any other command which needs './blobtools2/blobtools' as an argument (eg, 'blobtools add'). 
Removing the platform argument produces the same error, and adds the previously-solved one about system incompatibility.

Hoping you might have some insight on this, and thanks in advance for your time!

**Comment by rjchallis** [comment]
Hi

To run the commands inside the container, there is no need for the `./blobtools2/` prefix as the blob tools command is in the PATH. So your command should work if you run it as
```
blobtools create \
 --fasta data/Tridacna_squamosina_flye_racon.fasta \
 --taxid 484284 \
 --taxdump taxdump \
 datasets/giant_clam
```

**Comment by BirdmanRidesAgain** [comment]
Works perfectly! Thanks- I'm not used to using docker yet, and I wasn't sure how to see the directory structure in there. Makes a bit more sense now.
